[package]
name = "graphlite"
version = "0.1.0"
authors = ["markosindustries"]
edition = "2018"

[dependencies]
sled = "0.19.0"
bitvec = "0.10.0"
# serde = "1.0.89"
# bincode = "1.1.2"
# rmp-serde = "0.13.7"